// export const tableList = [];

export const tableList = [
  {
    id: "1.",
    action: "Scanned a Grade 1 Paddy Rice",
    commodity: "Paddy Rice",
    user: "Samuel Adeniyi",
    status: "Accepted",
    result: "Grade 1",
    date: "October 30, 2017",
  },

  {
    id: "2.",
    action: "Scanned a commodity",
    commodity: "Wheat",
    user: "Chidi Nnadi",
    status: "Rejected",
    result: "Not up to standard",
    date: "May 20, 2015",
  },

  {
    id: "3.",
    action: "Error while scanning",
    commodity: "Groundnut",
    user: "Green Onyeji",
    status: "Accepted",
    result: "Grade 2",
    date: "February 29, 2012",
  },

  {
    id: "4.",
    action: "May 1st 2021",
    commodity: "Cocoa Beans",
    user: "Victory Onya",
    status: "Rejected",
    result: "Not up to standard",
    date: "March 23, 2013",
  },

  {
    id: "5.",
    action: "May 1st 2021",
    commodity: "Soy Beans",
    user: "Mustapha Akanni",
    status: "Accepted",
    result: "Grade 2",
    date: "July 14, 2015",
  },

  {
    id: "6.",
    action: "May 1st 2021",
    commodity: "Maize",
    user: "Ayanfe Oluwa",
    status: "Accepted",
    result: "Grade 3",
    date: "February 28, 2018",
  },

  {
    id: "7.",
    action: "May 1st 2021",
    commodity: "Dried Split Ginger",
    user: "Victory Onya",
    status: "Accepted",
    result: "Grade 1",
    date: "May 12, 2019",
  },

  {
    id: "8.",
    action: "May 1st 2021",
    commodity: "Millet",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "December 2, 2018",
  },
  {
    id: "9.",
    action: "May 1st 2021",
    commodity: "Chilli Pepper",
    user: "Samuel Adeniyi",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 9, 2015",
  },

  {
    id: "10.",
    action: "May 1st 2021",
    commodity: "Sorghum",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 11, 2014",
  },

  {
    id: "11.",
    action: "Scanned a Grade 1 Paddy Rice",
    commodity: "Paddy Rice",
    user: "Samuel Adeniyi",
    status: "Accepted",
    result: "Grade 1",
    date: "October 30, 2017",
  },

  {
    id: "12.",
    action: "Scanned a commodity",
    commodity: "Wheat",
    user: "Chidi Nnadi",
    status: "Rejected",
    result: "Not up to standard",
    date: "May 20, 2015",
  },

  {
    id: "13.",
    action: "Error while scanning",
    commodity: "Groundnut",
    user: "Green Onyeji",
    status: "Accepted",
    result: "Grade 2",
    date: "February 29, 2012",
  },

  {
    id: "14.",
    action: "May 1st 2021",
    commodity: "Cocoa Beans",
    user: "Victory Onya",
    status: "Rejected",
    result: "Not up to standard",
    date: "March 23, 2013",
  },

  {
    id: "15.",
    action: "May 1st 2021",
    commodity: "Soy Beans",
    user: "Mustapha Akanni",
    status: "Accepted",
    result: "Grade 2",
    date: "July 14, 2015",
  },

  {
    id: "16.",
    action: "May 1st 2021",
    commodity: "Maize",
    user: "Ayanfe Oluwa",
    status: "Accepted",
    result: "Grade 3",
    date: "February 28, 2018",
  },

  {
    id: "17.",
    action: "May 1st 2021",
    commodity: "Dried Split Ginger",
    user: "Victory Onya",
    status: "Accepted",
    result: "Grade 1",
    date: "May 12, 2019",
  },

  {
    id: "18.",
    action: "May 1st 2021",
    commodity: "Millet",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "December 2, 2018",
  },
  {
    id: "19.",
    action: "May 1st 2021",
    commodity: "Chilli Pepper",
    user: "Samuel Adeniyi",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 9, 2015",
  },

  {
    id: "20.",
    action: "May 1st 2021",
    commodity: "Sorghum",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 11, 2014",
  },

  {
    id: "21.",
    action: "Scanned a Grade 1 Paddy Rice",
    commodity: "Paddy Rice",
    user: "Samuel Adeniyi",
    status: "Accepted",
    result: "Grade 1",
    date: "October 30, 2017",
  },

  {
    id: "22.",
    action: "Scanned a commodity",
    commodity: "Wheat",
    user: "Chidi Nnadi",
    status: "Rejected",
    result: "Not up to standard",
    date: "May 20, 2015",
  },

  {
    id: "23.",
    action: "Error while scanning",
    commodity: "Groundnut",
    user: "Green Onyeji",
    status: "Accepted",
    result: "Grade 2",
    date: "February 29, 2012",
  },

  {
    id: "24.",
    action: "May 1st 2021",
    commodity: "Cocoa Beans",
    user: "Victory Onya",
    status: "Rejected",
    result: "Not up to standard",
    date: "March 23, 2013",
  },

  {
    id: "25.",
    action: "May 1st 2021",
    commodity: "Soy Beans",
    user: "Mustapha Akanni",
    status: "Accepted",
    result: "Grade 2",
    date: "July 14, 2015",
  },

  {
    id: "26.",
    action: "May 1st 2021",
    commodity: "Maize",
    user: "Ayanfe Oluwa",
    status: "Accepted",
    result: "Grade 3",
    date: "February 28, 2018",
  },

  {
    id: "27.",
    action: "May 1st 2021",
    commodity: "Dried Split Ginger",
    user: "Victory Onya",
    status: "Accepted",
    result: "Grade 1",
    date: "May 12, 2019",
  },

  {
    id: "28.",
    action: "May 1st 2021",
    commodity: "Millet",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "December 2, 2018",
  },
  {
    id: "29.",
    action: "May 1st 2021",
    commodity: "Chilli Pepper",
    user: "Samuel Adeniyi",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 9, 2015",
  },

  {
    id: "30.",
    action: "May 1st 2021",
    commodity: "Sorghum",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 11, 2014",
  },

  {
    id: "31.",
    action: "Scanned a Grade 1 Paddy Rice",
    commodity: "Paddy Rice",
    user: "Samuel Adeniyi",
    status: "Accepted",
    result: "Grade 1",
    date: "October 30, 2017",
  },

  {
    id: "32.",
    action: "Scanned a commodity",
    commodity: "Wheat",
    user: "Chidi Nnadi",
    status: "Rejected",
    result: "Not up to standard",
    date: "May 20, 2015",
  },

  {
    id: "33.",
    action: "Error while scanning",
    commodity: "Groundnut",
    user: "Green Onyeji",
    status: "Accepted",
    result: "Grade 2",
    date: "February 29, 2012",
  },

  {
    id: "34.",
    action: "May 1st 2021",
    commodity: "Cocoa Beans",
    user: "Victory Onya",
    status: "Rejected",
    result: "Not up to standard",
    date: "March 23, 2013",
  },

  {
    id: "35.",
    action: "May 1st 2021",
    commodity: "Soy Beans",
    user: "Mustapha Akanni",
    status: "Accepted",
    result: "Grade 2",
    date: "July 14, 2015",
  },

  {
    id: "36.",
    action: "May 1st 2021",
    commodity: "Maize",
    user: "Ayanfe Oluwa",
    status: "Accepted",
    result: "Grade 3",
    date: "February 28, 2018",
  },

  {
    id: "37.",
    action: "May 1st 2021",
    commodity: "Dried Split Ginger",
    user: "Victory Onya",
    status: "Accepted",
    result: "Grade 1",
    date: "May 12, 2019",
  },

  {
    id: "38.",
    action: "May 1st 2021",
    commodity: "Millet",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "December 2, 2018",
  },
  {
    id: "39.",
    action: "May 1st 2021",
    commodity: "Chilli Pepper",
    user: "Samuel Adeniyi",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 9, 2015",
  },

  {
    id: "40.",
    action: "May 1st 2021",
    commodity: "Sorghum",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 11, 2014",
  },

  {
    id: "41.",
    action: "Scanned a Grade 1 Paddy Rice",
    commodity: "Paddy Rice",
    user: "Samuel Adeniyi",
    status: "Accepted",
    result: "Grade 1",
    date: "October 30, 2017",
  },

  {
    id: "42.",
    action: "Scanned a commodity",
    commodity: "Wheat",
    user: "Chidi Nnadi",
    status: "Rejected",
    result: "Not up to standard",
    date: "May 20, 2015",
  },

  {
    id: "43.",
    action: "Error while scanning",
    commodity: "Groundnut",
    user: "Green Onyeji",
    status: "Accepted",
    result: "Grade 2",
    date: "February 29, 2012",
  },

  {
    id: "44.",
    action: "May 1st 2021",
    commodity: "Cocoa Beans",
    user: "Victory Onya",
    status: "Rejected",
    result: "Not up to standard",
    date: "March 23, 2013",
  },

  {
    id: "45.",
    action: "May 1st 2021",
    commodity: "Soy Beans",
    user: "Mustapha Akanni",
    status: "Accepted",
    result: "Grade 2",
    date: "July 14, 2015",
  },

  {
    id: "46.",
    action: "May 1st 2021",
    commodity: "Maize",
    user: "Ayanfe Oluwa",
    status: "Accepted",
    result: "Grade 3",
    date: "February 28, 2018",
  },

  {
    id: "47.",
    action: "May 1st 2021",
    commodity: "Dried Split Ginger",
    user: "Victory Onya",
    status: "Accepted",
    result: "Grade 1",
    date: "May 12, 2019",
  },

  {
    id: "48.",
    action: "May 1st 2021",
    commodity: "Millet",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "December 2, 2018",
  },
  {
    id: "49.",
    action: "May 1st 2021",
    commodity: "Chilli Pepper",
    user: "Samuel Adeniyi",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 9, 2015",
  },

  {
    id: "50.",
    action: "May 1st 2021",
    commodity: "Sorghum",
    user: "Green Onyeji",
    status: "Rejected",
    result: "Not up to standard",
    date: "February 11, 2014",
  },
];
